import logo from "/logo.svg";
import dish from "/dish.jpg";
import dough from "/dough.jpg";
import favicon from "/favicon.ico";
import chalkfood from "/chalk-food.jpg";
import menu from "/menu.svg";
import oven from "/oven.jpg";
import pizza from "/pizza.svg";
import pizza1 from "/pizza1.jpg";
